### ISSUE TITLE
It looks interesting.. but what is it?

### ISSUE THREAD

**Issue by twirrim** [doubleleft/hook#110]
The documentation really does a bad job of explaining what exactly hook is.  Back end as a service?  That covers a whole huge multitude of possibilities :)

At the very least you should consider your README.md file to be a piece of marketing.  You need an elevator pitch, something that in a few sentences explains exactly what hook is, and what its value proposition is 

e.g. (speaking as someone still figuring out what hook actually does, and this is pretty terrible because I haven't really grasped the value it provides)  
"hook is a PHP framework that provides an easy way to handle common back end tasks such as x,y, and z, making it easy to produce a fully featured website"

At the very least I'd encourage you to add to the README a quick example of what it can provide, and what advantages hook gives over coding it myself.

In the wiki you also seem to be jumping in to sections without really explaining terms for the first time, assuming people are coming from the same concept of terminology as yourself.  e.g:

https://github.com/doubleleft/hook/wiki/Seeding-collections

"Seeding is the easiest way to populate your default application's data.
To generate a collection seed file, run generate:seed {collection_name} from commandline."

What's a collection?  Why would I want one?  Is it my application?  A collection of functions?  a schema (you're talking about seeding it with initial data)?  Your example uses the name "awesome_collection" which doesn't help, I'd encourage you to use a descriptive name that can aid in understanding.
When you get to https://github.com/doubleleft/hook/wiki/Collection-observers it seems like a collection is a function or task, e.g. you're referencing an auth collection?  Or is auth an item of a collection?

Hope this helps..

**Comment by endel** [comment]
Thanks very much for your feedback @twirrim.

We are now improving our documentation.
