### ISSUE TITLE
Not on buttons.heroku.com

### ISSUE THREAD

**Issue by jonmountjoy** [doubleleft/hook#125]
Hello!  

We pinged on Twitter.

I've tracked down why this isn't showing on buttons.heroku.com as you enquired - it's because the app.json is not on master - you've only got it on a branch.  If you move it to master and ping me, it should automagically show.  Otherwise, you can wait until we get a fix into buttons (unknown for now, I'd have to look at it).

Thanks
Jon

**Comment by endel** [comment]
Got it! It's now showing up there :)

Thanks for your time @jonmountjoy!

**Comment by jonmountjoy** [comment]
My pleasure @endel
