### ISSUE TITLE
Post installation question

### ISSUE THREAD

**Issue by dekhaus** [doubleleft/hook#146]
Hi

I stumbled upon Hook while searching for something else.  I installed it using the 'curl' command.  Unfortunately after successfully installing it and opening a new terminal window (for s&g's) - I don't have 'access' to the 'hook' command.  

Did I miss a step ?

Thanks
Dave

**Comment by endel** [comment]
Hey @dekhaus,

That's unusual. Could you please tell the operation system are you using, and the output of the entire CURL command?

I've just installed it successfully on my local machine and the output was the following: https://gist.github.com/endel/39a53f5fa4370f76d872

**Comment by dekhaus** [comment]
Hi.

I'm running MacOS 10.10.2 (Yosemite).

Here's a link to a pastie containing the output of running the curl install command -> http://pastie.org/10214426

Thanks
Dave

**Comment by endel** [comment]
@dekhaus thanks for taking your time for this detailed report.

At the end of the installation script, your `~/.bash_profile` should have a line to include `~/bin` into your $PATH:

```
# ~/.bash_profile
export PATH=~/bin:$PATH
```
Maybe there is something before the `export` line that is going wrong, and it is not exporting the PATH.

Anyway, you may use the complete path to execute the commandline tool: 

```
cd ~/p/php/hook # your local hook installation directory
~/bin/hook server
~/bin/hook app:new my-app
```

Please let me know if you find any problem.
