### ISSUE TITLE
problem with angularjs/angular-ui-router

### ISSUE THREAD

**Issue by jijijrey** [doubleleft/hook#152]
`hook
       .auth
       .login({email: username, password: password})
       .then(function(data) {
           console.log('user: ', data);
           $location.path = ('/');
       }, function(data) {
           console.log('error: ', data);
       });`

after a success login, won't navigate or redirect to $location.path

**Comment by endel** [comment]
Hi @jijijrey,

I'm not an angular specialist, but isn't `$location.path()` a method? Does it works this way? 

``` javascript
 $location.path('/')
```

hook has an angular-based administration panel which works fine. Here's the code example: https://github.com/doubleleft/hook-admin/blob/master/app/js/src/authentication.js#L43-L68

**Comment by jijijrey** [comment]
hi @endel ,

yep, it supposedly redirect to the path being define. I tried removing the hook and just use
`$location.path('/')` 
and it is working.

and base on your code example, it is also said that $location.path is not working:
[https://github.com/doubleleft/hook-admin/blob/master/app/js/src/authentication.js#L29-L34](https://github.com/doubleleft/hook-admin/blob/master/app/js/src/authentication.js#L29-L34)

**Comment by endel** [comment]
Hi @jijijrey, I think this might solve the issue: http://stackoverflow.com/a/11932283/892698

I'm closing this issue since its not related to this project :)

Thanks for checking out this project, feel free to have a chat on gitter if you get into any trouble!
