### ISSUE TITLE
Geo location Query

### ISSUE THREAD

**Issue by santoshgistto** [doubleleft/hook#153]
##how get the data depending on geo location

**Comment by endel** [comment]
Hi @santoshgistto,

Currently hook don't expose any geo-spatial method to the clients. Some database engines does provide it in some way, but currently there is no general way of creating and querying them independently of what engine is being used. 

It's always possible to create [a custom route](http://doubleleft.github.io/hook-userguide/The-Basics/Custom-routes/) and expose the data you need by yourself, by [querying the database](http://doubleleft.github.io/hook-userguide/The-Basics/Collections/#querying-the-database) manually.
