### ISSUE TITLE
Is Hook thrown?

### ISSUE THREAD

**Issue by PaulMaly** [doubleleft/hook#155]

**Comment by endel** [comment]
Hi @PaulMaly, what do you mean?

**Comment by PaulMaly** [comment]
I mean that last release was about year ago and seems that Hook was thrown.

**Comment by endel** [comment]
We don't have a new version release planned, as a matter of interest of the maintainers and the community. I do believe that this project has potential to achieve higher results and better standards. 

I personally use hook for quick agency projects every now and then.

If you happen to find any bug or feature request just do it, we're here to help.

Cheers!
